### ISSUE TITLE
Aggiunta vincoli esterni

### ISSUE THREAD

**Issue by ghost** [Chaos-Rat/GAO#2]
Bisogna aggiungere i vincoli esterni per l'annullamento e modifica dopo la data di inizio di un'asta per:
- asta (solo annullamento permesso, bisogna aggiungere un attributo opzionale per la dex. annullamento);
- lotto;
- articolo.

**Comment by ghost** [comment]
Ti sei dimenticato di mettere l'attributo descrizione_annullamento opzionale nello schema E/R (basta mettere 0, 1 sulla linea).

**Comment by papiscoulasbuscas** [comment]
fatto.
